---
# Install snort packages

- name: unwanted packages are removed
  package:
    name: "{{ snort_packages_remove }}"
    state: absent
  become: true
  when: snort_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ snort_packages_repos }}"
    state: "{{ snort_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ snort_packages_prereq }}"
    state: "{{ snort_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ snort_packages_install }}"
    state: "{{ snort_packages_state }}"
  become: true
